In [1]:
import numpy as np

In [2]:
def f(t):
    return (t[0] - 3) ** 2 - t[0] * t[1] + 3 * t[1] ** 2 

def grad_f(t):
    t1 = 2 * t[0] - 1 * t[1] - 6
    t2 = -1 * t[0] + 6 * t[1]
    return np.array([t1, t2])

def H(t):
    return np.array([[2,-1], [-1,6]])

x0 = [-8.6, -8.6]
x = np.array([x0])
lambda_ = []

In [3]:
#just for the first iteration
S0 = -grad_f(x[0])
S = np.array([S0])
print("S0:",np.round(S[0],4))

lambda_.append(- np.dot(grad_f(x[0]), S[0][None,:].T) / np.dot(S[0], np.dot(H(x[0]), S[0][None,:].T)))
print("lambda0:",np.round(lambda_[0],4))

x1 = x[0] + lambda_[0] * S[0]
x = np.append(x, [x1], axis=0)
print("x1:", np.round(x[1],4))

S0: [14.6 43. ]
lambda0: [0.2009]
x1: [-5.6669  0.0386]


In [4]:
A0 = np.array([[1,0], [0,1]])
A = np.array([A0])
# how to append elemets in A!!!    A = np.append(A, [[[1,1], [1,1]]], axis=0)
print(A)
#Acor[k] = 
delta_x = (x[1] - x[0])[None,:]
delta_g = grad_f(x[1]) - grad_f(x[0])[None,:]
Acor01 = np.dot(delta_x.T, delta_x) / np.dot(delta_x, delta_g.T) 
Acor02 = np.dot(np.dot(np.dot(A[0], delta_g.T), delta_g), A[0]) / np.dot(np.dot(delta_g, A[0]), delta_g.T)
Acor0 = Acor01 - Acor02
#A = np.append(A, [[A[k-1] + Acor[k]]], axis=0) -----two on one pair of []?
A1 = A0 + Acor0
A = np.append(A, [A1], axis=0)
#Sk = - A[k] * grad_f(x[k])
#S = np.append(S, [Sk], axis=0) -----two on one pair of []?
S1 = - np.dot(A1, grad_f(x[1]))
S = np.append(S, [S1], axis=0)

[[[1 0]
  [0 1]]]


In [5]:
Acor0

array([[ 0.01756205,  0.11767607],
       [ 0.11767607, -0.81666422]])

In [6]:
A1

array([[1.01756205, 0.11767607],
       [0.11767607, 0.18333578]])

In [7]:
grad_f(x[1])

array([-17.37239009,   5.89853245])

In [8]:
 S1

array([16.98336871,  0.96290258])

In [9]:
lambda_.append(- np.dot(grad_f(x[1]), S[1][None,:].T) / np.dot(S[1], np.dot(H(x[1]), S[1][None,:].T)))
print("lambda1:",np.round(lambda_[1],4))

x2 = x[1] + lambda_[1] * S[1]
x = np.append(x, [x2], axis=0)
print("x2:", np.round(x[2],4))

lambda1: [0.5264]
x2: [3.2727 0.5455]


In [10]:
delta_x = (x[2] - x[1])[None,:]
delta_g = grad_f(x[2]) - grad_f(x[1])[None,:]
Acor11 = np.dot(delta_x.T, delta_x) / np.dot(delta_x, delta_g.T) 
Acor12 = np.dot(np.dot(np.dot(A[1], delta_g.T), delta_g), A[1]) / np.dot(np.dot(delta_g, A[1]), delta_g.T)
Acor1 = Acor11 - Acor12
#A = np.append(A, [[A[k-1] + Acor[k]]], axis=0) -----two on one pair of []?
A2 = A1 + Acor1
#Sk = - A[k] * grad_f(x[k])
#S = np.append(S, [Sk], axis=0) -----two on one pair of []?
S2 = - np.dot(A2, grad_f(x[2]))
S = np.append(S, [S2], axis=0)

In [11]:
np.linalg.inv(H(1))

array([[0.54545455, 0.09090909],
       [0.09090909, 0.18181818]])

In [12]:
A2

array([[0.54545455, 0.09090909],
       [0.09090909, 0.18181818]])

In [23]:
round(np.dot(np.dot(S[1], H(1)), S[0].T),12)

0.0