In [1]:
import numpy as np

In [2]:
def f(x):
    return 3 * x[0] ** 2 + x[0] * x[1] + 2 * x[1] ** 2

def grad_f(t):
    t1 = 6 * t[0] + t[1]
    t2 = 4 * t[1] + t[0]
    return np.array([t1, t2])

def H(t):
    return np.matrix([[6,1], [1,4]])

x = [[6,4]]
#x = np.array(x0)
S = []

In [3]:
grad_f(x[0])

array([40, 22])

In [4]:
for i in range(0,3):
    if i == 0 or i == 1:
        S.append(-grad_f(x[i]))
    elif i == 2:
        S.append(x[2] - x[0])
    lambda_opt = - np.matrix(grad_f(x[i])) * np.matrix(S[i]).T / (np.matrix(S[i]) * H(x[i]) * np.matrix(S[i]).T)
    print(lambda_opt)
    x.append(x[i] + float(lambda_opt) * S[i])

[[0.15673887]]
[[0.27624602]]
[[0.00415192]]


In [5]:
S

[array([-40, -22]),
 array([ 1.06558363, -1.93742479]),
 array([-5.97519151, -3.98346101])]

In [10]:
x

[[6, 4],
 array([-0.26955475,  0.55174489]),
 array([0.02480849, 0.01653899]),
 array([ 7.97972799e-17, -1.31838984e-16])]

In [12]:
np.round(x[3],10)

array([ 0., -0.])