In [11]:
import numpy as np

In [12]:
def f(x):
    return 3 * x[0] ** 2 + x[0] * x[1] + 2 * x[1] ** 2

def grad_f(t):
    t1 = 6 * t[0] + t[1]
    t2 = 4 * t[1] + t[0]
    return np.array([t1, t2])

def H(t):
    return np.matrix([[6,1], [1,4]])

x = [[6,4]]
#x = np.array(x0)
S = []
#S = np.array([])
#lambda_const = 1

In [13]:
x[0]

[6, 4]

In [14]:
for i in range(0,3):
    S.append(-grad_f(x[i]))
    lambda_opt = - np.matrix(grad_f(x[i])) * np.matrix(S[i]).T / (np.matrix(S[i]) * H(x[i]) * np.matrix(S[i]).T)
    print(lambda_opt)
    x.append(x[i] + float(lambda_opt) * S[i])

[[0.15673887]]
[[0.27624602]]
[[0.15673887]]


In [15]:
S

[array([-40, -22]),
 array([ 1.06558363, -1.93742479]),
 array([-0.16538992, -0.09096446])]

In [16]:
x

[[6, 4],
 array([-0.26955475,  0.55174489]),
 array([0.02480849, 0.01653899]),
 array([-0.00111454,  0.00228133])]