In [20]:
import numpy as np

In [21]:
def f(x):
    return 3 * x[0] ** 2 + x[0] * x[1] + 2 * x[1] ** 2

def grad_f(x):
    return np.array([6 * x[0] + x[1], 4 * x[1] + x[0]])

x = [[6,4]]
#x = np.array(x0)
S = []
#S = np.array([])
lambda_const = 1

In [22]:
x[0]

[6, 4]

In [23]:
for i in range(0,3):
    S.append(- grad_f(x[i]) / np.linalg.norm(grad_f(x[i])))
    x.append(x[i] + lambda_const * S[i])

In [24]:
S

[array([-0.87621591, -0.48191875]),
 array([-0.87239669, -0.48879854]),
 array([-0.86743917, -0.49754325])]

In [25]:
x

[[6, 4],
 array([5.12378409, 3.51808125]),
 array([4.2513874 , 3.02928271]),
 array([3.38394823, 2.53173946])]