In [9]:
import numpy as np

In [21]:
def f(t):
    return 3 * (t[0] - 5) ** 2 + (t[1] - 4) ** 2

x0 = [0, 0] #to get rid of 0 index
x1 = np.array([8, 7])
x2 = np.array([10, 9])
x3 = np.array([8, 9])

x = np.array([x0, x1, x2, x3])
ksi = 1

In [22]:
f([4,6])

7

In [40]:
x0 = [0, 0]
x1 = np.array([5, 6])
x2 = np.array([4, 6])
x3 = np.array([4, 5])

x = np.array([x0, x1, x2, x3])

points = [x[1], x[2], x[3]]
func = [f(x[1]), f(x[2]), f(x[3])]
res = dict(zip(func, points))
res_sorted = sorted(res.items())
x_h = res_sorted[2][1]
x_g = res_sorted[1][1]
x_l= res_sorted[0][1]

IndexError: list index out of range

In [41]:
x_g = np.array([5, 6])
x_h = np.array([4, 6])
x_l = np.array([4, 5])

print("x_h:", x_h, "f(x_h):", f(x_h))
print("x_g:", x_g, "f(x_g):", f(x_g))
print("x_l:", x_l, "f(x_l):", f(x_l))

x_c = (x_g + x_l) / 2
print("x_c:", x_c)

x_new = 2 * x_c - x_h
print("x_new:", x_new, "f(x_new):", f(x_new))


x_h: [4 6] f(x_h): 7
x_g: [5 6] f(x_g): 4
x_l: [4 5] f(x_l): 4
x_c: [4.5 5.5]
x_new: [5. 5.] f(x_new): 1.0


In [46]:
tetta = -1/2
x_j = x_h + (1 + tetta) * (x_c - x_h)
print("Next x:", x_j, "f:", f(x_j))
f(x_j)
#np.append(x, x_j)

x_reduction = x_l + 0.5 * ([4,6] - x_l)
x_reduction

Next x: [4.25 5.75] f: 4.75


array([4. , 5.5])

In [52]:
#критерий окончания
x_l = np.array([4.5, 5.5])
x_h = np.array([4, 5.5])
x_g = np.array([4, 5])
x_c = (x_g + x_l + x_h) / 3

np.sqrt((1/3) * ((f(x_h) - f(x_c)) ** 2 + 
                (f(x_g) - f(x_c)) ** 2 + 
                (f(x_l) - f(x_c)) ** 2))

0.9468922527255178

In [53]:
x_c

array([4.16666667, 5.33333333])

array([7, 7])

In [11]:
class Vector(object):
    def __init__(self, x, y):
        """ Create a vector, example: v = Vector(1,2) """
        self.x = x
        self.y = y

    def __repr__(self):
        return "({0}, {1})".format(self.x, self.y)

    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Vector(x, y)

    def __sub__(self, other):
        x = self.x - other.x
        y = self.y - other.y
        return Vector(x, y)

    def __rmul__(self, other):
        x = self.x * other
        y = self.y * other
        return Vector(x, y)

    def __truediv__(self, other):
        x = self.x / other
        y = self.y / other
        return Vector(x, y)

    def c(self):
        return (self.x, self.y)
        
# objective f8 unction
def f(point):
    x, y = point
    return 3 * (x - 4) ** 2 + (y - 2) ** 2

def nelder_mead(alpha=1, beta=0.5, gamma=2, maxiter=10):
    
    # initialization
    v1 = Vector(7, 5)
    v2 = Vector(9, 7)
    v3 = Vector(7, 7)

    for i in range(maxiter):
        adict = {v1:f(v1.c()), v2:f(v2.c()), v3:f(v3.c())}
        points = sorted(adict.items(), key=lambda x: x[1])
        
        b = points[0][0]
        g = points[1][0]
        w = points[2][0]
        
        
        mid = (g + b)/2

        # reflection
        xr = mid + alpha * (mid - w)
        if f(xr.c()) < f(g.c()):
            w = xr
        else:
            if f(xr.c()) < f(w.c()):
                w = xr
            c = (w + mid)/2
            if f(c.c()) < f(w.c()):
                w = c
        if f(xr.c()) < f(b.c()):

            # expansion
            xe = mid + gamma * (xr - mid)
            if f(xe.c()) < f(xr.c()):
                w = xe
            else:
                w = xr
        if f(xr.c()) > f(g.c()):
            
            # contraction
            xc = mid + beta * (w - mid)
            if f(xc.c()) < f(w.c()):
                w = xc

        # update points
        v1 = w
        v2 = g
        v3 = b
        print(v1, v2, v3)
    return b

print("Result of Nelder-Mead algorithm: ")
xk = nelder_mead()
print("Best poits is: %s"%(xk))

Result of Nelder-Mead algorithm: 
(3.0, 4.0) (7, 7) (7, 5)
(3.0, 2.0) (7, 5) (3.0, 4.0)
(4.0, 3.5) (3.0, 4.0) (3.0, 2.0)
(4.0, 1.5) (3.0, 2.0) (4.0, 3.5)
(3.75, 2.375) (4.0, 3.5) (4.0, 1.5)
(3.90625, 2.328125) (3.75, 2.375) (4.0, 1.5)
(3.90234375, 2.029296875) (4.0, 1.5) (3.90625, 2.328125)
(3.92822265625, 2.009033203125) (3.90625, 2.328125) (3.90234375, 2.029296875)
(3.91754150390625, 1.941925048828125) (3.90234375, 2.029296875) (3.92822265625, 2.009033203125)
(3.94342041015625, 1.921661376953125) (3.91754150390625, 1.941925048828125) (3.92822265625, 2.009033203125)
Best poits is: (3.92822265625, 2.009033203125)
